kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: base
  name: base-deploy
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create","delete","update","get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create","delete"]
