# node 节点 proxy 角色绑定
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-node-proxy
subjects:
  - kind: ServiceAccount
    name: kube-node
    namespace: default
roleRef:
  kind: ClusterRole
  name: system:node-proxier
  apiGroup: rbac.authorization.k8s.io
