# 该脚本 无法执行成功  可通过 kubectl create sa app 创建
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  namespace: default
  labels:
    kubernetes.io/cl:uster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
