apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    qcloud-app: consul-client
  name: consul-client
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      qcloud-app: consul-client
  template:
    metadata:
      labels:
        qcloud-app: consul-client
    spec:
      containers:
      - args:
        - agent
        - -ui
        - -client=0.0.0.0
        - -join=10.3.1.15
        env:
        - name: APPLICATION_NAME
          value: consul-client
        - name: TAG
          value: test
        image: consul:1.3.0
        imagePullPolicy: Always
        name: consul-client
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 512Mi
      restartPolicy: Always
