kind: Endpoints
apiVersion: v1
metadata:
  name: master-service
subsets:
  - addresses:
      - ip: 10.254.0.88
    ports:
      - port: 6443
  - addresses:
      - ip: 10.254.0.89
    ports:
      - port: 6443
  - addresses:
      - ip: 10.254.0.90
    ports:
      - port: 6443
