- hosts: all
  tasks:
    - name: edit hostname
      template: 
        src: ~/k8s-ansible/template/hostname.j2
        dest: /etc/hostname
    - name: copy hosts to /etc/hosts
      copy: 
        src: ~/k8s-ansible/customer/hosts
        dest: /etc/hosts
    - name: mkdir conf dir /etc/kubernetes
      file:
        path=/etc/kubernetes
        state=directory
    - name: mkdir log dir /var/log/kubernetes
      file:
        path=/var/log/kubernetes
        state=directory
    - name: disable all nodes firewalld.service
      shell: systemctl disable firewalld.service
    - name: stop all nodes firewalld.service
      shell: systemctl stop firewalld.service
