- hosts: all
  tasks:
    - name: mkdir conf dir /etc/kubenetes
      file:
        path=/etc/kubernetes
        state=directory
    - name: disable all nodes firewalld.service
      shell: systemctl disable firewalld.service
    - name: stop all nodes firewalld.service
      shell: systemctl stop firewalld.service
