- hosts: k8s-build
  tasks: 
    - name: make master dir binaries
      file:
        path=~/k8s-ansible/binaries/master
        state=directory
    - name: download master binaries
      shell: wget http://blog.liu-kevin.com/content/images/uploader/k8s/binaries/1.6.0/master/{{ item.service }} -o ~/k8s-ansible/binaries/master/{{ item.service }}
      with_items:
        - {service: 'etcd'}
        - {service: 'etcdctl'}
        - {service: 'kube-apiserver'}
        - {service: 'kube-controller-manager'}
        - {service: 'kubectl'}
        - {service: 'kube-scheduler'}

    - name: make node dir binaries
      file:
        path=~/k8s-ansible/binaries/node
        state=directory
    - name: download node binaries
      shell: wget http://blog.liu-kevin.com/content/images/uploader/k8s/binaries/1.6.0/node/{{ item.service }} -o ~/k8s-ansible/binaries/node/{{ item.service }}
      with_items:
        - {service: 'kubectl'}
        - {service: 'kubelet'}
        - {service: 'kube-proxy'}
    
