- hosts: k8s-build
  tasks: 
    - name: install nginx
      shell: yum install -y nginx
    - name: copy nginx conf
      template:
        src: ~/k8s-ansible/template/master-nginx.conf.j2
        dest: /etc/nginx/conf.d/master-nginx.conf
    #- name: 重启nginx  #此处无ca证书文件，启动会报错
    #  shell: nginx
    - name: make master dir binaries  #创建master二进制文件临时存储目录
      file:
        path=~/k8s-ansible/binaries/master
        state=directory
    - name: make node dir binaries  #创建node二进制文件临时存储目录
      file:
        path=~/k8s-ansible/binaries/node
        state=directory
    - name: download etcd binaries    #下载etcd二进制文件
      get_url: 
        dest: ~/k8s-ansible/binaries/master/{{ item.service }}
        url: http://blog.liu-kevin.com/content/images/uploader/k8s/binaries/1.6.0/master/{{ item.service }}
      with_items:
        - {service: 'etcd'}
        - {service: 'etcdctl'}

    - name: download master binaries  #下载master节点的二进制文件
      get_url: 
        dest: ~/k8s-ansible/binaries/master/{{ item.service }}
        url: http://blog.liu-kevin.com/content/images/uploader/k8s/binaries/1.9.8/{{ item.service }}
      with_items:
        - {service: 'kube-apiserver'}
        - {service: 'kube-controller-manager'}
        - {service: 'kubectl'}
        - {service: 'kube-scheduler'}
    - name: download node binaries  #下载node节点的二进制文件
      get_url: 
        dest: ~/k8s-ansible/binaries/node/{{ item.service }}
        url: http://blog.liu-kevin.com/content/images/uploader/k8s/binaries/1.6.0/node/{{ item.service }}
      with_items:
        - {service: 'kubectl'}
        - {service: 'kubelet'}
        - {service: 'kube-proxy'}
    - name: download flanneld binaries  #下载flanneld所的二进制文件
      get_url:
        url: http://blog.liu-kevin.com/content/images/uploader/fannel/v0.10.0/{{item.service}}
        dest: ~/k8s-ansible/binaries/node/{{ item.service }}
      with_items:
        - { service: 'flanneld'}
        - { service: 'mk-docker-opts.sh'} 
