- hosts: k8s-build
  tasks: 
    - name: make master dir binaries
      file:
        path=~/k8s-ansible/binaries/master
        state=directory
    - name: make node dir binaries
      file:
        path=~/k8s-ansible/binaries/node
        state=directory
    - name: download etcd binaries
      get_url: 
        dest: ~/k8s-ansible/binaries/master/{{ item.service }}
        url: http://blog.liu-kevin.com/content/images/uploader/k8s/binaries/1.6.0/master/{{ item.service }}
      with_items:
        - {service: 'etcd'}
        - {service: 'etcdctl'}

    - name: download master binaries
      get_url: 
        dest: ~/k8s-ansible/binaries/master/{{ item.service }}
        url: http://blog.liu-kevin.com/content/images/uploader/k8s/binaries/1.9.8/{{ item.service }}
      with_items:
        - {service: 'kube-apiserver'}
        - {service: 'kube-controller-manager'}
        - {service: 'kubectl'}
        - {service: 'kube-scheduler'}

    - name: make node dir binaries
      file:
        path=~/k8s-ansible/binaries/node
        state=directory
    - name: download node binaries
      get_url: 
        dest: ~/k8s-ansible/binaries/node/{{ item.service }}
        url: http://blog.liu-kevin.com/content/images/uploader/k8s/binaries/1.6.0/node/{{ item.service }}      
      with_items:
        - {service: 'kubectl'}
        - {service: 'kubelet'}
        - {service: 'kube-proxy'}
    - name: download flanneld binaries
      get_url:
        url: http://blog.liu-kevin.com/content/images/uploader/fannel/v0.10.0/{{item.service}}
        dest: ~/k8s-ansible/binaries/node/{{ item.service }}
      with_items:
        - { service: 'flanneld'}
        - { service: 'mk-docker-opts.sh'} 
