- hosts: k8s-master
  tasks: 
    - name: make etcd  dir /var/lib/etcd/
      file:
        path=/var/lib/etcd/
        state=directory
    - name: produce master conf
      template: 
        src: ~/k8s-ansible/template/{{item.service}}.j2
        dest: /etc/kubenetes/{{item.service}}
      with_items:
        - {service: 'apiserver'}
        - {service: 'controller-manager'}
        - {service: 'scheduler'}
    - name: install master binaries
      copy: 
        src: ~/k8s-ansible/binaries/master/{{item.service}}
        dest: /usr/bin/{{item.service}}
      with_items:
        - {service: 'etcd'}
        - {service: 'kube-apiserver'}
        - {service: 'kube-controller-manager'}
        - {service: 'kube-scheduler'}
        - {service: 'etcdctl'}
        - {service: 'kubectl'}
    - name: copy master systemctl service
      copy:
        src: ~/k8s-ansible/systemctl/master/{{item.service}}.service
        dest: /usr/lib/systemd/system/{{item.service}}.service
      with_items:
        - {service: 'etcd'}
        - {service: 'kube-apiserver'}
        - {service: 'kube-controller-manager'}
        - {service: 'kube-scheduler'}
    - name: enable master service
      shell:  systemctl enable {{item.service}}.service
      with_items:
        - {service: 'etcd'}
        - {service: 'kube-apiserver'}
        - {service: 'kube-controller-manager'}
        - {service: 'kube-scheduler'}
    - name: start  master service
      shell:  systemctl start {{item.service}}.service
      with_items:
        - {service: 'etcd'}
        - {service: 'kube-apiserver'}
        - {service: 'kube-controller-manager'}
        - {service: 'kube-scheduler'}









