- hosts: k8s-nodes
  tasks: 
    - name: install docker  # 安装docker
      shell: yum install -y docker-1.13.1-75.git8633870.el7.centos.x86_64
    - name: mkdir /var/lib/kubelet  # 创建kubelet lib目录
      file:
        path: /var/lib/kubelet
        state: directory
    - name: produce node conf  # 生成服务启动配置文件
      template: 
        src: ~/k8s-ansible/template/{{item.service}}.j2
        dest: /etc/kubernetes/{{item.service}}
      with_items:
        - {service: 'kubelet'}
        - {service: 'proxy'}
    - name: copy kubeconfig to .kube/ # 复制kubeconfig
      copy: 
        src: ~/k8s-ansible/cert/kubeconfig
        dest: ~/.kube/config
    - name: install node binaries #安装二进制服务
      copy: 
        src: ~/k8s-ansible/binaries/node/{{item.service}}
        dest: /usr/bin/{{item.service}}
        mode: 744
      with_items:
        - {service: 'kubectl'}
        - {service: 'kubelet'}
        - {service: 'kube-proxy'}
    - name: copy node systemctl service  # 复制systemctl 启动文件
      copy:
        src: ~/k8s-ansible/systemctl/node/{{item.service}}.service
        dest: /usr/lib/systemd/system/{{item.service}}.service
      with_items:
        - {service: 'kubelet'}
        - {service: 'kube-proxy'}
        - {service: 'docker'}
    - name: reload systemctl config  # 重新加载systemctl config
      shell: systemctl daemon-reload
    - name: restart docker   #修改了docker配置文件，重启docker 服务
      shell: systemctl restart docker.service
    - name: enable node service  # 开机启用k8s服务
      shell:  systemctl enable {{item.service}}.service
      with_items:
        - {service: 'kubelet'}
        - {service: 'kube-proxy'}
    - name: start  node service  # 启动k8s服务
      shell:  systemctl start {{item.service}}.service
      with_items:
        - {service: 'kubelet'}
        - {service: 'kube-proxy'}
    - name: pull images pause-amd64  # 下载pod所需的基础镜像pause-amd64
      shell:  docker pull registry.cn-beijing.aliyuncs.com/kevin-public/pause-amd64:3.0
    - name: tag pause-amd64  # 对pause-amd64 tag处理
      shell:  docker tag registry.cn-beijing.aliyuncs.com/kevin-public/pause-amd64:3.0  gcr.io/google_containers/pause-amd64:3.0
      
    - name: pull kube-dns images # 下载dns需要的镜像
      shell: docker pull registry.cn-beijing.aliyuncs.com/kevin-public/{{item.image}}:1.14.1
      with_items:
      - {image: 'k8s-dns-kube-dns-amd64'}
      - {image: 'k8s-dns-dnsmasq-nanny-amd64'}
      - {image: 'k8s-dns-sidecar-amd64'}
    - name: tag kube-dns images #对dns镜像进行tag
      shell: docker tag registry.cn-beijing.aliyuncs.com/kevin-public/{{item.image}}:1.14.1  gcr.io/google_containers/{{item.image}}:1.14.1
      with_items:
      - {image: 'k8s-dns-kube-dns-amd64'}
      - {image: 'k8s-dns-dnsmasq-nanny-amd64'}
      - {image: 'k8s-dns-sidecar-amd64'}
