- hosts: k8s-masters
  tasks: 
    - name: produce master conf  # 生成 master服务配置文件
      template: 
        src: ~/k8s-ansible/template/kubeconfig.j2
        dest: ~/k8s-ansible/bin/kubeconfig.sh
        mode: 744
    - name: make controller manager kubeconfig
      shell: ~/k8s-ansible/bin/kubeconfig.sh kube-controller-manager
    - name: make scheduler kubeconfig
      shell: ~/k8s-ansible/bin/kubeconfig.sh kube-scheduler
    - name: mkdir .kube
      file:
        path=~/.kube
        state=directory
    - name: make kubectl kubeconfig
      shell: ~/k8s-ansible/bin/kubeconfig.sh cluster-admin
    - name: cp kubectl config
      shell: cp /opt/kubernetes/conf/cluster-admin.kubeconfig ~/.kube/config
    - name: enable master service  # 开机自启动服务
      shell:  systemctl enable {{item.service}}.service
      with_items:
        - {service: 'kube-controller-manager'}
        - {service: 'kube-scheduler'}
    - name: start  master service  # 启动服务
      shell:  systemctl start {{item.service}}.service
      with_items:
        - {service: 'kube-controller-manager'}
        - {service: 'kube-scheduler'}
    - name: kubelet bootstrap
      shell: kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap
    - name: make kubelet bootstrp config shell
      template:
        src: ~/k8s-ansible/template/kube-bootstrap.j2
        dest: ~/k8s-ansible/bin/kube-bootstrap.sh
        mode: 744
    - name: exec kube bootstrap shell
      shell: ~/k8s-ansible/bin/kube-bootstrap.sh  kubelet-bootstrap
    - name: kube proxy kubeconfig
      shell: ~/k8s-ansible/bin/kubeconfig.sh kube-proxy






