- hosts: k8s-nodes
  tasks: 
    - name: install containerd  # 安装docker
      shell: yum install -y containerd.io
    - name: cp containerd conf config.toml
      copy:
        src: ~/k8s-ansible/conf/config.toml
        dest: /etc/containerd/config.toml
    - name: restart containerd
      shell: systemctl restart containerd
    - name: enable containerd
      shell: systemctl enable containerd
    - name: cp ssl
      copy: /opt/kubernetes/ssl/{{item.service}}
      dest: /opt/kubernetes/ssl/{{item.service}}
      with_items:
        - {service: 'ca.pem'}
        - {service: 'kube-proxy.pem'}
        - {service: 'kube-proxy-key.pem'}
    - name: cp bootstrap config
      copy:
        src: /opt/kubenetes/conf/kubelet-bootstrap.kubeconfig
        dest: /opt/kubernetes/conf/kubelet-bootstrap.kubeconfig
    - name: produce node conf  # 生成服务启动配置文件
      template: 
        src: ~/k8s-ansible/template/{{item.service}}.j2
        dest: /opt/kubernetes/conf/kubernetes/{{item.service}}.yml
      with_items:
        - {service: 'kube-proxy-config.yml'}
        - {service: 'kube-proxy.conf'}
        - {service: 'kubelet-config.yml'}
        - {service: 'kubelet.conf'}
    - name: install node binaries #安装二进制服务
      copy: 
        src: ~/k8s-ansible/binaries/node/{{item.service}}
        dest: /usr/bin/{{item.service}}
        mode: 744
      with_items:
        - {service: 'kubelet'}
        - {service: 'kube-proxy'}
    - name: copy node systemctl service  # 复制systemctl 启动文件
      copy:
        src: ~/k8s-ansible/systemctl/node/{{item.service}}.service
        dest: /usr/lib/systemd/system/{{item.service}}.service
      with_items:
        - {service: 'kubelet'}
        - {service: 'kube-proxy'}
#        - {service: 'docker'}
    - name: reload systemctl config  # 重新加载systemctl config
      shell: systemctl daemon-reload
#    - name: restart docker   #修改了docker配置文件，重启docker 服务
#      shell: systemctl restart docker.service
    - name: enable node service  # 开机启用k8s服务
      shell:  systemctl enable {{item.service}}.service
      with_items:
        - {service: 'kubelet'}
        - {service: 'kube-proxy'}
    - name: start  node service  # 启动k8s服务
      shell:  systemctl start {{item.service}}.service
      with_items:
        - {service: 'kubelet'}
        - {service: 'kube-proxy'}
#    - name: pull images pause-amd64  # 下载pod所需的基础镜像pause-amd64
#      shell:  docker pull registry.cn-beijing.aliyuncs.com/kevin-public/pause-amd64:3.0
#    - name: tag pause-amd64  # 对pause-amd64 tag处理
#      shell:  docker tag registry.cn-beijing.aliyuncs.com/kevin-public/pause-amd64:3.0  gcr.io/google_containers/pause-amd64:3.0
      
#    - name: pull kube-dns images # 下载dns需要的镜像
#      shell: docker pull registry.cn-beijing.aliyuncs.com/kevin-public/{{item.image}}:1.14.1
#      with_items:
#      - {image: 'k8s-dns-kube-dns-amd64'}
#      - {image: 'k8s-dns-dnsmasq-nanny-amd64'}
#      - {image: 'k8s-dns-sidecar-amd64'}
#    - name: tag kube-dns images #对dns镜像进行tag
      shell: docker tag registry.cn-beijing.aliyuncs.com/kevin-public/{{item.image}}:1.14.1  gcr.io/google_containers/{{item.image}}:1.14.1
#      with_items:
#      - {image: 'k8s-dns-kube-dns-amd64'}
#      - {image: 'k8s-dns-dnsmasq-nanny-amd64'}
#      - {image: 'k8s-dns-sidecar-amd64'}
