
- hosts: k8s-build
  tasks:
    - name: deal kubedns-svc.yaml # 处理k8s dns service yaml文件
      template:
        src: ~/k8s-ansible/template/kubedns-svc.j2
        dest: ~/k8s-ansible/dns/kubedns-svc.yaml
    - name: deal kubedns-controller.yaml  # 处理k8s dns controller yaml文件
      template:
        src: ~/k8s-ansible/template/kubedns-controller.j2
        dest: ~/k8s-ansible/dns/kubedns-controller.yaml
    - name: k8s create cm sa svc controller   # 创建k8s dns sa cm svc controller
      shell: kubectl create -f ~/k8s-ansible/dns/{{item.yml}}
      with_items:
      - {yml: 'kubedns-cm.yaml'}
      - {yml: 'kubedns-sa.yaml'}
      - {yml: 'kubedns-svc.yaml'}
      - {yml: 'kubedns-controller.yaml'}
