- hosts: k8s-nodes
  tasks:
    - name: copy flannel binaries to nodes
      copy:
        src: ~/k8s-ansible/systemctl/node/flanneld.service
        dest: /usr/lib/systemd/system/flanneld.service
    - name: copy flannel.service to nodes
      copy:
        src: ~/k8s-ansible/binaries/node/{{item.service}}
        dest: /usr/bin/{{item.service}}
        mode: u+x  
      with_items:
        - { service: 'flanneld'}
        - { service: 'mk-docker-opts.sh'}
    - name: chmod mk-docker-opts.sh
      shell: chmod u+x /usr/bin/mk-docker-opts.sh
    - name: copy flannel config
      template:
        src: ~/k8s-ansible/template/flannel.j2
        dest: /etc/sysconfig/flanneld
    - name: stop docker 
      shell: systemctl stop docker.service
    - name: load systemctl conf
      shell: systemctl daemon-reload    
    - name: start flanneld
      shell: systemctl start flanneld.service
    - name: config docker0 network ip 1
      shell: mk-docker-opts.sh -i
    - name: config docker0 network ip 2
      shell: source /run/flannel/subnet.env
    - name: config docker0 network ip 3
      shell: ifconfig docker0 ${FLANNEL_SUBNET}
    - name: start docker
      shell: systemctl restart docker




