- hosts: k8s-nodes
  tasks:
    - name: pull images istio images  # 下载istio官方镜像
      shell:  docker pull registry.cn-beijing.aliyuncs.com/kube_image/{{item.service}}:1.1.4
      with_items:
        - {service: 'citadel'}
        - {service: 'kubectl'}
        - {service: 'galley'}
        - {service: 'proxyv2'}
        - {service: 'pilot'}
        - {service: 'mixer'}
        - {service: 'sidecar_injector'}
    - name: tag istio images  # 对istio镜像重新tag
      shell:  docker tag registry.cn-beijing.aliyuncs.com/kube_image/{{item.service}}:1.1.4  docker.io/istio/{{item.service}}:1.1.4
      with_items:
        - {service: 'citadel'}
        - {service: 'kubectl'}
        - {service: 'galley'}
        - {service: 'proxyv2'}
        - {service: 'pilot'}
        - {service: 'mixer'}
        - {service: 'sidecar_injector'}
    - name: pull images istio other images  # 下载istio所需的其它镜像
      shell:  docker pull registry.cn-beijing.aliyuncs.com/kube_image/{{item.service}}
      with_items:
        - {service: 'grafana:6.0.2'}
        - {service: 'all-in-one:1.9'}
        - {service: 'kiali:v0.16'}
    - name: tag images istio other images # 对istio所需的其它镜像重新tag
      shell: docker tag registry.cn-beijing.aliyuncs.com/kube_image/{{item.service}}:{{item.version}}  docker.io/{{item.tagPrefix}}/{{item.service}}:{{item.version}}
      with_items:
        - {service: 'grafana', version: '6.0.2', tagPrefix: 'docker.io/grafana/'}
        - {service: 'all-in-one', version: '1.9', tagPrefix: 'docker.io/jaegertracing/'}
        - {service: 'kiali', version: 'v0.16', tagPrefix: 'docker.io/kiali/'}
    - name: pull images istio prometheus  # 下载 prometheus
      shell:  docker pull registry.cn-beijing.aliyuncs.com/kevin-public/prometheus:v2.3.1
    - name: tag images istio prometheus # 对prometheus重新tag
      shell: docker tag registry.cn-beijing.aliyuncs.com/kevin-public/prometheus:v2.3.1  docker.io/prom/prometheus:v2.3.1




